steps:

- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: [
    'build',
    '-t', '${_IMAGE_NAME}:${TAG_NAME}',
    '-t', '${_IMAGE_NAME}:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  args: [
    'run',
    '--rm',
    '--entrypoint', 'py.test',
    '${_IMAGE_NAME}:latest',
  ]
  waitFor: [ 'build' ]

images:
  - '${_IMAGE_NAME}:${TAG_NAME}'
  - '${_IMAGE_NAME}:latest'

timeout: 600s
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/github.com/globalfishingwatch/pipe-events'
options:
  dynamic_substitutions: true

