version: '2'
services:
  pipe_events:
    image: gfw/pipe-events
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  gcloud:
    image: gfw/pipe-events
    build: .
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

  py.test:
    image: gfw/pipe-events
    build: .
    entrypoint: py.test
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  bash:
    image: gfw/pipe-events
    build: .
    entrypoint: /bin/bash
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true


