services:
  pipeline:
    image: gfw/pipe-events
    build:
      context: .
      target: dev
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: /bin/bash

  gcloud:
    image: google/cloud-sdk:latest
    build: .
    entrypoint: gcloud
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  test:
    image: gfw/pipe-events-test
    # Runs tests using the production Docker image.
    # Intended to be executed in the GitHub CI environment.
    build:
      context: .
      target: test
    entrypoint: "pytest -v"

# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true
