version: '2'
services:
  pipeline:
    image: gfw/pipe-events
    build: .
    volumes:
      - ".:/opt/project"
      - "~/.config/gcloud:/root/.config/gcloud"

  py.test:
    image: gfw/pipe-events
    build: .
    entrypoint:
      - py.test
    volumes:
      - ".:/opt/project"
      - "~/.config/gcloud:/root/.config/gcloud"
