#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
source ${THIS_SCRIPT_DIR}/pipeline.sh
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  DATE_RANGE \
  SOURCE_MESSAGES \
  SOURCE_SEGMENT_VESSEL \
  SOURCE_SEGS \
  SOURCE_VI_SSVID_BY_YEAR \
  ALL_VESSELS_BYYEAR_V_TABLE \
  SOURCE_SPATIAL_MEASURES \
  REGIONS_TABLE \
  VESSEL_IDENTITY_CORE \
  VESSEL_IDENTITY_AUTHORIZATION \
  FISHING_LIST \
  DEST_TABLE_NAME
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  echo -e "\nUsage:\n${0} ${ARGS[*]}\n"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

ARG_VALUES=("$@")
PARAMS=()
for index in ${!ARGS[*]}; do
  echo "${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
if [[ -z $END_DATE ]]; then
  END_DATE=${START_DATE}
fi

################################################################################
# Check fishing list parameter and set correct filters
################################################################################

# Define FISHING_LIST_ENUMS
FISHING_LIST_ENUMS=( "restrictive" "less_restrictive" )

# Check if the fishing list is a valid enum
if [[ ! " ${FISHING_LIST_ENUMS[@]} " =~ " ${FISHING_LIST} " ]]; then
  echo "Invalid fishing list parameter. Valid values are: ${FISHING_LIST_ENUMS}"
  exit 1
fi

# Check if FISHING_LIST is restrictive
if [[ ${FISHING_LIST} == "less_restrictive" ]]; then
  FISHING_LIST_FILTERS="potential_fishing OR on_fishing_list_sr"
fi

if [[ ${FISHING_LIST} == "restrictive" ]]; then
  FISHING_LIST_FILTERS="prod_shiptype = 'fishing'"
fi

echo "${FISHING_LIST} fishing list filters: ${FISHING_LIST_FILTERS}"

################################################################################

end_date_minus_one_day=$(date --date="${END_DATE} -1 day" +%Y-%m-%d)

end_date_no_hyphens=${END_DATE//-}
end_date_minus_one_day_no_hyphens=${end_date_minus_one_day//-}

current_table_name="${DEST_TABLE_NAME}_v${end_date_no_hyphens}"
one_day_previous_table_name="${DEST_TABLE_NAME}_v${end_date_minus_one_day_no_hyphens}"
current_table_name_fishing_events="${DEST_TABLE_NAME}_temp_${FISHING_LIST}_v${end_date_no_hyphens}"

view_name="${DEST_TABLE_NAME}"

echo "Current table=${current_table_name}"
echo "Current one_day_previous_table_name=${one_day_previous_table_name}"


################################################################################
# Force that the destination tables exists
################################################################################
echo "Ensuring events table ${current_table_name} exists"

TABLE_DESC=(
  'This table was generated using the next query:'
  'https://github.com/GlobalFishingWatch/pipe-events/blob/release_pipe_3/assets/bigquery/fishing-events-1.sql.j2'
  'https://github.com/GlobalFishingWatch/pipe-events/blob/release_pipe_3/assets/bigquery/fishing-events-2.sql.j2'
  ' '
  ' '
  'Sources:'
  '========='
  "* Script: ${BASH_SOURCE[0]}"
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Command:"
  "$(basename $0)"
  "$@"
  ' '
  ' '
  'Maintainers:'
  '============='
  'Data: Willa Brooks <willa@globalfishingwatch.org>'
  'Engineer: Álvaro Perdiz <alvaro@globalfishingwatch.org>'
  ' '
  ' '
)

TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json

# Current table
bq mk --force \
  --label environment:production \
  --label resource_creator:gcp-composer \
  --label project:events \
  --label version:v1 \
  --label step:generate_events \
  --label stage:productive \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field=event_start \
  --time_partitioning_type=MONTH \
  "${current_table_name}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${DEST_TABLE_NAME}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Delete existing records
################################################################################
DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
jinja2 ${DELETE_SQL} \
  -D table=${current_table_name//:/.} \
  -D start_date=${START_DATE} \
  -D end_date=${END_DATE} \
  | bq query --max_rows=0
if [ "$?" -ne 0 ]; then
  echo "  Unable to delete records for table ${current_table_name} from ${START_DATE} to ${END_DATE}"
  exit 1
fi

################################################################################
# Inserting new records
################################################################################
INSERT_SQL=${ASSETS}/bigquery/fishing-events-1.sql.j2

echo "SQl query: ${INSERT_SQL}"
echo "Creating temporal table with fishing-events ${START_DATE} to ${END_DATE}"

jinja2 "${INSERT_SQL}" \
   -D messages="${SOURCE_MESSAGES}" \
   -D start_date="${START_DATE}" \
   -D end_date="${END_DATE}" \
   -D segs="${SOURCE_SEGS}" \
   -D segment_vessel=${SOURCE_SEGMENT_VESSEL} \
   -D vi_ssvid_by_year=${SOURCE_VI_SSVID_BY_YEAR} \
   -D all_vessels_byyear=${ALL_VESSELS_BYYEAR_V_TABLE} \
   -D spatial_measures_table=${SOURCE_SPATIAL_MEASURES} \
   -D regions_table=${REGIONS_TABLE//:/.} \
   -D vessel_identity_core=${VESSEL_IDENTITY_CORE//:/.} \
   -D vessel_identity_authorization=${VESSEL_IDENTITY_AUTHORIZATION//:/.} \
   -D fishing_list_filters="${FISHING_LIST_FILTERS}" \
   | bq query --headless --max_rows=0 --allow_large_results \
     --append_table \
     --destination_table ${current_table_name_fishing_events}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${current_table_name_fishing_events} from ${START_DATE} to ${END_DATE}"
  exit 1
fi
bq update --expiration 3600 ${current_table_name_fishing_events}

INSERT_SQL=${ASSETS}/bigquery/fishing-events-2.sql.j2

echo "SQl query: ${INSERT_SQL}"
echo "Inserting new records for ${START_DATE} to ${END_DATE}"

jinja2 "${INSERT_SQL}" \
   -D messages="${SOURCE_MESSAGES}" \
   -D start_date="${START_DATE}" \
   -D end_date="${END_DATE}" \
   -D segs="${SOURCE_SEGS}" \
   -D segment_vessel=${SOURCE_SEGMENT_VESSEL} \
   -D vi_ssvid_by_year=${SOURCE_VI_SSVID_BY_YEAR} \
   -D all_vessels_byyear=${ALL_VESSELS_BYYEAR_V_TABLE} \
   -D spatial_measures_table=${SOURCE_SPATIAL_MEASURES} \
   -D regions_table=${REGIONS_TABLE//:/.} \
   -D vessel_identity_core=${VESSEL_IDENTITY_CORE//:/.} \
   -D vessel_identity_authorization=${VESSEL_IDENTITY_AUTHORIZATION//:/.} \
   -D fishing_list_filters="${FISHING_LIST_FILTERS}" \
   -D source_fishing_events=${current_table_name_fishing_events//:/.} \
   | bq query --headless --max_rows=0 --allow_large_results \
     --append_table \
     --destination_table ${current_table_name}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${current_table_name} from ${START_DATE} to ${END_DATE}"
  echo "Removing temporal table [${current_table_name_fishing_events}]"
  bq rm -f -t "${current_table_name_fishing_events}"
  exit 1
fi

################################################################################
# Remove temporal table
################################################################################
echo "Removing temporal table [${current_table_name_fishing_events}]"
bq rm -f -t "${current_table_name_fishing_events}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to remove two days before table ${current_table_name_fishing_events}"
  exit 1
fi

################################################################################
# Create new view
################################################################################
echo "Creating view [${view_name}]"
echo "CREATE OR REPLACE VIEW ${view_name} AS SELECT * FROM ${current_table_name//:/.}"

bq query \
  --use_legacy_sql=false \
  "CREATE OR REPLACE VIEW ${view_name//:/.} AS SELECT * FROM ${current_table_name//:/.}"

bq update \
  --set_label environment:production \
  --set_label resource_creator:gcp-composer \
  --set_label project:events \
  --set_label version:v1 \
  --set_label step:generate_events \
  --set_label stage:productive \
  --description "${TABLE_DESC}" \
  ${view_name}

bq update \
  ${view_name} \
  ${SCHEMA}

if [ "$?" -ne 0 ]; then
  echo "  Unable to create view ${view_name}"
  exit 1
fi


################################################################################
# Remove prev table
################################################################################
echo "Removing temporal table [${one_day_previous_table_name}]"
bq rm -f -t "${one_day_previous_table_name}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to remove two days before table ${one_day_previous_table_name}"
  exit 1
fi

echo "${DEST_TABLE_NAME} Done."
