#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
source ${THIS_SCRIPT_DIR}/pipeline.sh
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  DATE_RANGE \
  MESSAGES_TABLE \
  EVENTS_TABLE \
  SEGMENT_VESSEL \
  VESSEL_INFO \
  MIN_POS_COUNT \
  MIN_DIST \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
	echo -e "\nUsage:\n$0 YYYY-MM-DD[,YYYY-MM-DD] MESSAGES_TABLE EVENTS_TABLE SEGMENT_VESSEL VESSEL_INFO MIN_POS_COUNT MIN_DIST\n"
	}


if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

ARG_VALUES=("$@")
PARAMS=()
for index in ${!ARGS[*]}; do
  echo "${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
if [[ -z $END_DATE ]]; then
  END_DATE=${START_DATE}
fi

echo "Running $0"
echo "  DATE_RANGE: $DATE_RANGE"
echo "  MESSAGES_TABLE: $MESSAGES_TABLE"
echo "  EVENTS_TABLE: $EVENTS_TABLE"
echo "  SEGMENT_VESSEL: $SEGMENT_VESSEL"
echo "  VESSEL_INFO: $VESSEL_INFO"
echo "  MIN_POS_COUNT: $MIN_POS_COUNT"
echo "  MIN_DIST: $MIN_DIST"

################################################################################
# Force that the destination table exists
################################################################################
echo "Ensuring events table ${EVENTS_TABLE} exists"
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${MESSAGES_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json
bq mk --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field=event_start \
  ${EVENTS_TABLE}
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${EVENTS_TABLE}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Delete existing records
################################################################################
DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
jinja2 ${DELETE_SQL} \
  -D table=${EVENTS_TABLE//:/.} \
  -D start_date=${START_DATE} \
  -D end_date=${END_DATE} \
  | bq query --max_rows=0
if [ "$?" -ne 0 ]; then
  echo "  Unable to delete records for table ${EVENTS_TABLE} from ${START_DATE} to ${END_DATE}"
  exit 1
fi

################################################################################
# Inserting new records
################################################################################
INSERT_SQL=${ASSETS}/bigquery/gap-events.sql.j2
echo "Inserting new records for ${START_DATE} to ${END_DATE}"
jinja2 ${INSERT_SQL} \
   -D source=${MESSAGES_TABLE//:/.} \
   -D dest=${EVENTS_TABLE//:/.} \
   -D start_date=${START_DATE} \
   -D end_date=${END_DATE} \
   -D min_pos_count=${MIN_POS_COUNT} \
   -D min_dist=${MIN_DIST} \
   -D segment_vessel=${SEGMENT_VESSEL//:/.} \
   -D vessel_info=${VESSEL_INFO//:/.} \
   | bq query --max_rows=0


if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${EVENTS_TABLE} from ${START_DATE} to ${END_DATE}"
  exit 1
fi

echo "${EVENTS_TABLE} Done."
