#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
source ${THIS_SCRIPT_DIR}/pipeline.sh
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  SOURCE_TABLE \
  SPATIAL_MEASURES_TABLE \
  REGIONS_TABLE \
  ALL_VESSELS_BYYEAR_V_TABLE \
  VESSEL_INFO_TABLE \
  VESSEL_IDENTITY_CORE \
  VESSEL_IDENTITY_AUTHORIZATION \
  DEST_TABLE \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  echo -e "\nUsage:\n$0 SOURCE_TABLE SPATIAL_MEASURES_TABLE REGIONS_TABLE ALL_VESSELS_BYYEAR_V_TABLE VESSEL_INFO_TABLE VESSEL_IDENTITY_CORE VESSEL_IDENTITY_AUTHORIZATION DEST_TABLE \n"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

ARG_VALUES=("$@")
PARAMS=()
for index in ${!ARGS[*]}; do
  echo "${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

echo "Running $0"
echo "  SOURCE_TABLE: $SOURCE_TABLE"
echo "  SPATIAL_MEASURES_TABLE: $SPATIAL_MEASURES_TABLE"
echo "  ALL_VESSELS_BYYEAR_V_TABLE: $ALL_VESSELS_BYYEAR_V_TABLE"
echo "  VESSEL_INFO_TABLE: $VESSEL_INFO_TABLE"
echo "  VESSEL_IDENTITY_CORE: $VESSEL_IDENTITY_CORE"
echo "  VESSEL_IDENTITY_AUTHORIZATION: $VESSEL_IDENTITY_AUTHORIZATION"
echo "  DEST_TABLE: $DEST_TABLE"
################################################################################
# Force that the destination table exists
################################################################################
echo "Ensuring events table ${DEST_TABLE} exists"
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${SOURCE_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json
bq mk --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field=event_start \
  --time_partitioning_type=MONTH \
  ${DEST_TABLE}
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${DEST_TABLE}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Inserting new records
################################################################################
echo "Regenerating records"
SQL=${ASSETS}/bigquery/encounter-events.sql.j2
jinja2 ${SQL} \
  -D encounters_table=${SOURCE_TABLE//:/.} \
  -D vessel_info_table=${VESSEL_INFO_TABLE//:/.} \
  -D all_vessels_byyear_v_table=${ALL_VESSELS_BYYEAR_V_TABLE//:/.} \
  -D spatial_measures_table=${SPATIAL_MEASURES_TABLE//:/.} \
  -D vessel_identity_core=${VESSEL_IDENTITY_CORE//:/.} \
  -D vessel_identity_authorization=${VESSEL_IDENTITY_AUTHORIZATION//:/.} \
  -D regions_table=${REGIONS_TABLE//:/.} \
  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${DEST_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${DEST_TABLE}"
  exit 1
fi

echo "${DEST_TABLE} Done."
