#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

display_usage() {
	echo "Available Commands"
	echo "  generate_encounter_events          publish encounter (vessel rendevouz at sea) events"
	echo "  generate_anchorage_events          publish port (port in and out) events"
	echo "  generate_fishing_events            publish continuous fishing message events"
  echo "  publish_postgres                   publish events of a given bigquery table to a postgres database"
	}


if [[ $# -le 0 ]]
then
    display_usage
    exit 1
fi


case $1 in

  generate_encounter_events)
    ${THIS_SCRIPT_DIR}/generate_encounter_events "${@:2}"
    ;;

  generate_anchorage_events)
    ${THIS_SCRIPT_DIR}/generate_anchorage_events "${@:2}"
    ;;

  generate_fishing_events)
    ${THIS_SCRIPT_DIR}/generate_fishing_events "${@:2}"
    ;;

  generate_loitering_events)
    ${THIS_SCRIPT_DIR}/generate_loitering_events "${@:2}"
    ;;

  publish_postgres)
    ${THIS_SCRIPT_DIR}/publish_postgres "${@:2}"
    ;;

  *)
    display_usage
    exit 1
    ;;
esac
