#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

display_usage() {
	echo "Available Commands"
	echo "  generate_loitering_events        Publish loitering events"
	echo "  generate_port_visits_events      Publish port visits events"
	echo "  generate_port_visits_events_v2   Publish port visits events v2"
	echo "  generate_fishing_events          Publish fishing events"
	echo "  generate_encounter_events       Publish encounter events"
}


if [[ $# -le 0 ]]
then
    display_usage
    exit 1
fi


case $1 in

  generate_encounter_events)
    ${THIS_SCRIPT_DIR}/generate_encounter_events "${@:2}"
    ;;

  generate_anchorage_events)
    ${THIS_SCRIPT_DIR}/generate_anchorage_events "${@:2}"
    ;;

  generate_fishing_events)
    ${THIS_SCRIPT_DIR}/generate_fishing_events "${@:2}"
    ;;

  generate_loitering_events)
    ${THIS_SCRIPT_DIR}/generate_loitering_events "${@:2}"
    ;;

  generate_port_visits_events)
    ${THIS_SCRIPT_DIR}/generate_port_visits_events "${@:2}"
    ;;

  generate_port_visits_events_v2)
    ${THIS_SCRIPT_DIR}/generate_port_visits_events_v2 "${@:2}"
    ;;

  publish_postgres)
    ${THIS_SCRIPT_DIR}/publish_postgres "${@:2}"
    ;;

  *)
    display_usage
    exit 1
    ;;
esac
